name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linting
        run: |
          bash ci-cd/scripts/run_lint.sh

      - name: Run tests
        run: |
          bash ci-cd/scripts/run_tests.sh

      - name: Build Docker images
        run: |
          bash ci-cd/scripts/build_and_push_docker.sh

      - name: Deploy to production
        run: |
          echo "Deploying to production..."  # Add your deployment commands here
